<a href="https://colab.research.google.com/github/pashahaha/datavisualization/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #
x1 = np.random.randint(1,10, size=6)
x2 = np.random.randint(1,10, size=(3,4))
x3 = np.random.randint(1,10, size=(3,4,5))

In [ ]:
print(x1)
print()
print(x2)
print()
print(x3)
print()

[1 9 8 9 7 5]

[[5 8 6 7]
 [2 6 9 3]
 [8 7 1 2]]

[[[1 6 1 6 7]
  [8 9 3 2 3]
  [1 4 1 2 3]
  [3 5 8 4 8]]

 [[7 7 6 1 8]
  [5 2 2 4 8]
  [2 4 2 5 8]
  [6 6 9 5 5]]

 [[7 1 3 3 9]
  [9 5 6 5 3]
  [3 8 9 2 2]
  [1 8 4 2 1]]]



Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [ ]:
print(np.arange(6,60,6))
print(np.linspace(0,180,num=10))

[ 6 12 18 24 30 36 42 48 54]
[  0.  20.  40.  60.  80. 100. 120. 140. 160. 180.]


In [ ]:
x1

array([1, 9, 8, 9, 7, 5])

In [ ]:
x1[4]

np.int64(7)

In [ ]:
x1[-1]

np.int64(5)

In [ ]:
x2

array([[5, 8, 6, 7],
       [2, 6, 9, 3],
       [8, 7, 1, 2]])

In [ ]:
x2[0,0]

np.int64(5)

In [ ]:
x2[0,1]

np.int64(8)

In [ ]:
x2[0,0] = 3.6768
x2

array([[3, 8, 6, 7],
       [2, 6, 9, 3],
       [8, 7, 1, 2]])

**Array Slicing; Accessing Subarrays**

x[start:stop:step]

In [ ]:
data = np.array ([1,2,3])

In [ ]:
data[0:3]

array([1, 2, 3])