<a href="https://colab.research.google.com/github/pashahaha/datavisualization/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #
x1 = np.random.randint(1,10, size=6)
x2 = np.random.randint(1,10, size=(3,4))
x3 = np.random.randint(1,10, size=(3,4,5))

In [2]:
print(x1)
print()
print(x2)
print()
print(x3)
print()

[8 5 9 5 3 5]

[[4 1 2 2]
 [9 2 8 4]
 [1 3 8 9]]

[[[7 3 4 6 9]
  [5 9 4 3 3]
  [5 6 2 8 6]
  [2 2 9 7 6]]

 [[8 9 9 1 4]
  [6 6 4 8 8]
  [8 3 5 8 1]
  [8 2 9 8 9]]

 [[1 6 1 8 9]
  [9 9 4 3 4]
  [1 5 1 7 2]
  [5 8 5 9 9]]]



Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [3]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [4]:
print(np.arange(6,60,6))
print(np.linspace(0,180,num=10))

[ 6 12 18 24 30 36 42 48 54]
[  0.  20.  40.  60.  80. 100. 120. 140. 160. 180.]


In [5]:
x1

array([8, 5, 9, 5, 3, 5])

In [6]:
x1[4]

np.int64(3)

In [7]:
x1[-1]

np.int64(5)

In [8]:
x2

array([[4, 1, 2, 2],
       [9, 2, 8, 4],
       [1, 3, 8, 9]])

In [9]:
x2[0,0]

np.int64(4)

In [10]:
x2[0,1]

np.int64(1)

In [11]:
x2[0,0] = 3.6768
x2

array([[3, 1, 2, 2],
       [9, 2, 8, 4],
       [1, 3, 8, 9]])

**Array Slicing; Accessing Subarrays**

x[start:stop:step]

In [12]:
data = np.array ([1,2,3])

In [13]:
data[0:3]

array([1, 2, 3])

# NumPy 2


In [14]:
x1 = np.random.randint(1,10, size=6) #1D array
x2 = np.random.randint(1,10, size=(4,4)) #2D array
x3 = np.random.randint(1,10, size=(6,3,3)) #3D array

In [15]:
print(x1)
print()
print(x2)
print()
print(x3)
print()

[3 7 4 5 6 4]

[[1 4 3 1]
 [6 9 9 2]
 [9 2 9 4]
 [5 4 3 9]]

[[[9 3 8]
  [8 3 6]
  [6 5 8]]

 [[6 6 4]
  [2 5 7]
  [4 5 3]]

 [[8 7 4]
  [9 3 5]
  [3 6 5]]

 [[6 3 1]
  [4 1 3]
  [2 8 8]]

 [[8 5 7]
  [5 8 1]
  [2 7 5]]

 [[1 5 8]
  [6 7 1]
  [7 2 4]]]



In [16]:
x2[:2, :3] #2 baris 3 kolom

array([[1, 4, 3],
       [6, 9, 9]])

In [17]:
x2[:3, ::1]

array([[1, 4, 3, 1],
       [6, 9, 9, 2],
       [9, 2, 9, 4]])

In [18]:
print(x2[:,0]) #kolom pertama x2

[1 6 9 5]


In [19]:
print(x2[0,:]) #baris pertama x2

[1 4 3 1]


In [20]:
print(x2[0])

[1 4 3 1]


##Extract


In [21]:
x2_sub = x2[:2,:2]
print(x2_sub)

[[1 4]
 [6 9]]


In [22]:
x2_sub[0,0] = 99
print(x2_sub)

[[99  4]
 [ 6  9]]


In [23]:
print(x2)

[[99  4  3  1]
 [ 6  9  9  2]
 [ 9  2  9  4]
 [ 5  4  3  9]]


##Creating copies of arrays


In [24]:
#Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the copy() method:

In [25]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  4]
 [ 6  9]]


In [26]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  4]
 [ 6  9]]


In [27]:
print(x2)

[[99  4  3  1]
 [ 6  9  9  2]
 [ 9  2  9  4]
 [ 5  4  3  9]]


# Reshaping of Arrays
Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the reshape method. For example, if you want to put the numbers 1 through 9 in a 3×3 grid, you can do the following:

In [29]:
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
x = np.array([1,2,3])

#row vector via reshape
x.reshape((1,3))

array([[1, 2, 3]])

In [32]:
#row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [33]:
#column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

# Array Concatenation and Splitting
All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

In [34]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [35]:
z = [99,99,99,]
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


It can also be used for two-dimensional arrays:

In [38]:
grid = np.array([[1,2,3],
                [4,5,6]])

In [39]:
#concatenate along the first axis
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [40]:
#conatenate along the second axis (zero-indexed)
np.concatenate([grid,grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [41]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                 [6,5,4]])

#vertically stack the arrays
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [42]:
#horizontally stack the arrays
y = np.array ([[99],
               [99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

## Splitting of arrays
The opposite of concatenation is splitting, which is implemented by the functions np.split, np.hsplit, and np.vsplit. For each of these, we can pass a list of indices giving the split points

In [48]:
x = [1,2,3,99,99,3,2,1]
x1,x2,x3 = np.split(x, [3,6])
print(x1, x2, x3)

[1 2 3] [99 99  3] [2 1]


In [49]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [51]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Mathematics

In [52]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


Problem Statement: Let's say there are four people and they already have some money and we want to give 2 to each one of them. How to do it in one go and do same for other mathematical operations too.

In [53]:
a + 2

array([3, 4, 5, 6])

In [54]:
a - 2

array([-1,  0,  1,  2])

In [55]:
a * 2

array([2, 4, 6, 8])

In [56]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [57]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [58]:
a ** 2

array([ 1,  4,  9, 16])

# Statistics

In [60]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
np.min(stats)

np.int64(1)

In [62]:
np.max(stats, axis=1)

array([3, 6])

In [63]:
np.sum(stats, axis=0)

array([5, 7, 9])