<a href="https://colab.research.google.com/github/pashahaha/datavisualization/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #
x1 = np.random.randint(1,10, size=6)
x2 = np.random.randint(1,10, size=(3,4))
x3 = np.random.randint(1,10, size=(3,4,5))

In [2]:
print(x1)
print()
print(x2)
print()
print(x3)
print()

[1 6 9 1 7 5]

[[2 2 4 3]
 [6 1 1 5]
 [4 2 2 1]]

[[[1 6 5 9 6]
  [3 9 4 6 4]
  [2 6 8 9 7]
  [8 6 6 6 7]]

 [[6 6 3 8 7]
  [8 8 6 2 3]
  [7 6 5 2 2]
  [9 9 1 3 4]]

 [[9 4 4 5 6]
  [5 6 3 4 4]
  [1 5 5 1 9]
  [2 5 2 1 8]]]



Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [3]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [4]:
print(np.arange(6,60,6))
print(np.linspace(0,180,num=10))

[ 6 12 18 24 30 36 42 48 54]
[  0.  20.  40.  60.  80. 100. 120. 140. 160. 180.]


In [5]:
x1

array([1, 6, 9, 1, 7, 5])

In [6]:
x1[4]

np.int64(7)

In [7]:
x1[-1]

np.int64(5)

In [8]:
x2

array([[2, 2, 4, 3],
       [6, 1, 1, 5],
       [4, 2, 2, 1]])

In [9]:
x2[0,0]

np.int64(2)

In [10]:
x2[0,1]

np.int64(2)

In [11]:
x2[0,0] = 3.6768
x2

array([[3, 2, 4, 3],
       [6, 1, 1, 5],
       [4, 2, 2, 1]])

**Array Slicing; Accessing Subarrays**

x[start:stop:step]

In [12]:
data = np.array ([1,2,3])

In [13]:
data[0:3]

array([1, 2, 3])

# NumPy 2


In [24]:
x1 = np.random.randint(1,10, size=6) #1D array
x2 = np.random.randint(1,10, size=(4,4)) #2D array
x3 = np.random.randint(1,10, size=(6,3,3)) #3D array

In [25]:
print(x1)
print()
print(x2)
print()
print(x3)
print()

[9 6 6 3 6 9]

[[9 8 2 2]
 [7 4 1 7]
 [3 5 9 2]
 [5 4 8 3]]

[[[2 6 2]
  [5 7 9]
  [8 3 7]]

 [[6 6 9]
  [6 6 6]
  [1 9 4]]

 [[9 5 1]
  [4 2 8]
  [7 7 3]]

 [[8 1 9]
  [8 9 2]
  [1 7 5]]

 [[1 4 8]
  [7 9 6]
  [5 9 3]]

 [[9 9 6]
  [4 6 9]
  [2 1 9]]]



In [30]:
x2[:2, :3] #2 baris 3 kolom

array([[9, 8, 2],
       [7, 4, 1]])

In [38]:
x2[:3, ::1]

array([[9, 8, 2, 2],
       [7, 4, 1, 7],
       [3, 5, 9, 2]])

In [41]:
print(x2[:,0]) #kolom pertama x2

[2 1 9 8]


In [42]:
print(x2[0,:]) #baris pertama x2

[9 8 2 2]


In [43]:
print(x2[0])

[9 8 2 2]


##Extract


In [44]:
x2_sub = x2[:2,:2]
print(x2_sub)

[[9 8]
 [7 4]]


In [45]:
x2_sub[0,0] = 99
print(x2_sub)

[[99  8]
 [ 7  4]]


In [46]:
print(x2)

[[99  8  2  2]
 [ 7  4  1  7]
 [ 3  5  9  2]
 [ 5  4  8  3]]


##Creating copies of arrays


In [ ]:
#Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the copy() method:

In [47]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  8]
 [ 7  4]]


In [48]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  8]
 [ 7  4]]


In [49]:
print(x2)

[[99  8  2  2]
 [ 7  4  1  7]
 [ 3  5  9  2]
 [ 5  4  8  3]]
